language: java
jdk:
        - oraclejdk8
before_install:
        - mysql -e 'CREATE DATABASE syslog'
install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
        - mysql
script:
        - mvn test
